# NerfExplosions by notablenoah
# https://github.com/notablenoah/NerfExplosions
#
#
# NerfExplosions lets you limit or increase explosion damage taken by players
# The default value is 0.5 meaning that players take 50% of the regular damage
multiplier: 0.5